### ISSUE TITLE
Adding DateShiftConfig | CharacterMaskConfig | CryptoHashConfig functionality as part of current de-identification process

### ISSUE THREAD

**Issue by manishadubaria** [GoogleCloudPlatform/healthcare-deid#13]
Implement similar functionality like DateShiftConfig, CharacterMaskConfig, and CryptoHashConfig of healthcare API in the current Code piece.
**DateShiftConfig**: By using this config code should transform dates by shifting them within a preset range. Could be very useful when you want date transformations to remain consistent across de-identification.
**CharacterMaskConfig**: BY using this config code should replace strings that correspond to the given infoTypes with a specified fixed character. For eg: Rather than redacting a patient's name, you can replace the name with a series of asterisks(*).
**CryptoHashConfig**: By using this config code can transform data by replacing values with cryptographic hashes. Could be useful when instead of redaction the values need to be hashed.

**Comment by dshumphr** [comment]
Hi and thanks for the feature request!

We’re aiming to keep this offline redaction library very lightweight and focused on basic redaction methods, while the more powerful Healthcare API will continue to provide more advanced features like those described here. If using the Healthcare API may fit your use case and you’d like more information on using it to perform DICOM deidentification, please see https://cloud.google.com/healthcare/docs/how-tos/dicom-deidentify.

Since we aren’t planning to expand the library to provide these more advanced features, I’m marking this issue closed. Thanks again for the request and your interest!
